ntm_contacts_query = '''
    SELECT
        new_contact_id AS ntm_id,
        first_name,
        middle_name,
        last_name,
        deal_id,
        budb_id,
        contact_group_id AS ntm_contact_group_id,
        md_address AS address,
        md_city AS city,
        md_state AS state_address,
        md_postalcode AS postal_code,
        input_address AS address2,
        input_city AS city2,
        input_state AS state_address2,
        input_postalcode AS postal_code2,
        address_data_source AS data_source,
        target_county AS country,
        target_state AS state,
        serial_number,
        old_serial_number,
        phone1,
        phone2,
        phone3,
        phone4,
        phone5,
        phone6,
        email1,
        email2,
        email3,
        email4,
        email5,
        email6
    FROM ntm_contacts
    WHERE new_contact_id IS NOT NULL;
'''